#!/usr/bin/env python3
"""
Generate curated training CSVs for ADC and fusion_protein classes.

Produces:
  data/external/curated/adc_curated.csv          (~150 entries)
  data/external/curated/fusion_protein_curated.csv (~100 entries)

Uses known therapeutic sequences as templates, then generates realistic
variants via controlled random mutagenesis (reproducible via fixed seed).
"""
import csv
import os
import sys

import numpy as np

# Ensure project root is on PYTHONPATH
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from src.training.features import compute_sequence_features

# ── Valid amino acids ──
AA = list("ACDEFGHIKLMNPQRSTVWY")

# ═══════════════════════════════════════════════════════════════════════
#  Known ADC antibody backbones (VH+CH / VL+CL full-length sequences)
# ═══════════════════════════════════════════════════════════════════════

# Trastuzumab (backbone of T-DM1 / trastuzumab emtansine, and T-DXd / trastuzumab deruxtecan)
TRASTUZUMAB_HC = (
    "EVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPG"
)
TRASTUZUMAB_LC = (
    "DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Brentuximab vedotin backbone (anti-CD30, chimeric IgG1)
BRENTUXIMAB_HC = (
    "QIQLQQSGPEVVKPGASVKISCKASGYTFTDYYITWVKQKPGQGLEWIGYIYPGSGSTNYNEKFKGKATLTADTSSSTAYMQLSSLTSEDSAVYFCANYGNYWFAYWGQGTQVTVSA"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
BRENTUXIMAB_LC = (
    "DIVLTQSPASLAVSLGQRATISCRASESVSIHGTHLMHWYQQKPGQPPKLLIYHTSRLHSGVPARFSGSGSGTDFTLTIDPVEADDAATYYCQQSFNVPPTFGAGTKLELK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Enfortumab vedotin backbone (anti-Nectin-4, human IgG1k)
ENFORTUMAB_HC = (
    "QVQLQQWGAGLLKPSETLSLTCAVYGGSFSGYYWSWIRQPPGKGLEWIGEINHSGSTNYNPSLKSRVTISVDTSKNQFSLKLSSVTAADTAVYYCARARGPWSFDPWGQGTLVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
ENFORTUMAB_LC = (
    "DIQMTQSPSSLSASVGDRVTITCRASQSISSYLNWYQQKPGKAPKLLIYAASSLQSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQSYSTPPITFGQGTRLEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Sacituzumab govitecan backbone (anti-Trop2, humanized IgG1k)
SACITUZUMAB_HC = (
    "EVQLVESGGGLVQPGGSLRLSCAASGFTFSSYNMSWVRQAPGKGLEWVSYISSGSSTIYYADSVKGRFTISRDNAKNSLYLQMNSLRDEDTAVYYCAKLGQNDDYWGQGTLVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
SACITUZUMAB_LC = (
    "DIQMTQSPSSLSASVGDRVTITCRASQGISNYLNWYQQKPGKAPKLLIYAASNLQSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQANSFPITFGQGTRLEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Polatuzumab vedotin backbone (anti-CD79b, humanized IgG1)
POLATUZUMAB_HC = (
    "EVQLVESGGGLVQPGGSLRLSCAASGYTFSSYWISWVRQAPGKGLEWIGHITPTTGSPTYAQKFQGRVTMTRDTSTSTVYMELSSLRSEDTAVYYCARERSGYFPYYYMDVWGKGTTVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
POLATUZUMAB_LC = (
    "DIQMTQSPSSLSASVGDRVTITCRASQDISNYLNWYQQKPGKAPKLLIYYTSRLHSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQGNTLPWTFGQGTKVEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Loncastuximab tesirine backbone (anti-CD19, humanized IgG1)
LONCASTUXIMAB_HC = (
    "EVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAISWVRQAPGQGLEWMGGIIPIFGTANYAQKFQGRVTITADESTSTAYMELSSLRSEDTAVYYCARGLWFGELYYMDVWGKGTTVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
LONCASTUXIMAB_LC = (
    "EIVLTQSPATLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQQRSNWPPTFGQGTKVEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Belantamab mafodotin backbone (anti-BCMA, humanized IgG1)
BELANTAMAB_HC = (
    "EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSGISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKDGITMVRGVIRYYYAMDYWGQGTLVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
BELANTAMAB_LC = (
    "DIQLTQSPSSLSASVGDRVTITCRASQGISSALAWYQQKPGKAPKLLIYDASNLESGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQFNSYPLTFGGGTKVEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Mirvetuximab soravtansine backbone (anti-FRa, humanized IgG1)
MIRVETUXIMAB_HC = (
    "QVQLVQSGAEVKKPGSSVKVSCKASGYTFTNYDINWVRQAPGQGLEWMGWIFPGDGSTQYAQKFQGRVTMTRNTSISTAYMELSGLTSDDTAVYYCARETTIVYSYYAMDYWGQGTSVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
MIRVETUXIMAB_LC = (
    "DIQMTQSPSSLSASVGDRVTITCQASQDISNYLNWYQQKPGKAPKLLIYDASNLETGVPSRFSGSGSGTDFTFTISSLQPEDIATYYCQHFDHLPLAFGGGTKVEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

# Tisotumab vedotin backbone (anti-TF, human IgG1)
TISOTUMAB_HC = (
    "QVQLVQSGAEVKKPGASVKVSCKASGYTFTGYYMHWVRQAPGQGLEWMGWINPNSGGTNYAQKFQGRVTMTRDTSISTAYMELSRLRSDDTAVYYCARSGNYYGSSYWGLLDYWGQGTLVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
TISOTUMAB_LC = (
    "QSALTQPASVSGSPGQSITISCTGTSSDVGGYNYVSWYQQHPGKAPKLMIYEVSNRPSGVSNRFSGSKSGNTASLTISGLQAEDEADYYCNSYTSSSTLWVFGGGTKLTVL"
    "GQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS"
)

# Disitamab vedotin backbone (anti-HER2, humanized IgG1)
DISITAMAB_HC = (
    "EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLEWVADVNPNSGGSIYNQRFKGRFTLSVDRSKNTLYLQMNSLRAEDTAVYYCARNSITTTFALDFWGQGTMVTVSS"
    "ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG"
    "PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEM"
    "TKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)
DISITAMAB_LC = (
    "DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIK"
    "RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
)

ADC_TEMPLATES = [
    ("trastuzumab_emtansine", TRASTUZUMAB_HC, TRASTUZUMAB_LC),
    ("trastuzumab_deruxtecan", TRASTUZUMAB_HC, TRASTUZUMAB_LC),
    ("brentuximab_vedotin", BRENTUXIMAB_HC, BRENTUXIMAB_LC),
    ("enfortumab_vedotin", ENFORTUMAB_HC, ENFORTUMAB_LC),
    ("sacituzumab_govitecan", SACITUZUMAB_HC, SACITUZUMAB_LC),
    ("polatuzumab_vedotin", POLATUZUMAB_HC, POLATUZUMAB_LC),
    ("loncastuximab_tesirine", LONCASTUXIMAB_HC, LONCASTUXIMAB_LC),
    ("belantamab_mafodotin", BELANTAMAB_HC, BELANTAMAB_LC),
    ("mirvetuximab_soravtansine", MIRVETUXIMAB_HC, MIRVETUXIMAB_LC),
    ("tisotumab_vedotin", TISOTUMAB_HC, TISOTUMAB_LC),
    ("disitamab_vedotin", DISITAMAB_HC, DISITAMAB_LC),
]

# ═══════════════════════════════════════════════════════════════════════
#  Known fusion protein sequences
# ═══════════════════════════════════════════════════════════════════════

# Etanercept (TNFR2-Fc)
ETANERCEPT_CHAIN = (
    "LPAQVAFTPYAPEPGSTCRLREYYDQTAQMCCSKCSPGQHAKVFCTKTSDTVCDSCEDSTYTQLWNWVPECLSCGSRCSSDQVETQACTREQNRICTCRPGWYCALSKQEGCRLCAPLRKCRPGFGVARPGTETSDVVCKPCAPGTFSNTTSSTDICRPHQICNVVAIPGNASMDAVCTSTSPTRSMAPGAVHLPQPVSTRSQHTQPTPEPSTAPSTSFLLPMGPSPPAEG"
    "STDEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Abatacept (CTLA4-Fc)
ABATACEPT_CHAIN = (
    "MHVAQPAVVLASSRGIASFVCEYASPGKATEVRVTVLRQADSQVTEVCAATYMMGNELTFLDDSICTGTSSGNQVNLTIQGLRAMDTGLYICKVELMYPPPYYLGIGNGTQIYVIDPEPCPDSD"
    "QEPKSSDKTHTSPSPAPELLGGSSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Belatacept (CTLA4-Fc variant, 2 AA mutations vs abatacept: A29Y, L104E in CTLA-4 domain)
BELATACEPT_CHAIN = (
    "MHVAQPAVVLASSRGIASFVCEYASPGKYTEVRVTVLRQADSQVTEVCAATYMMGNELTFLDDSICTGTSSGNQVNLTIQGLRAMDTGLYICKVELMYPPPYYLGIGNGTQIYVIDPEPCPDSD"
    "QEPKSSDKTHTSPSPAPELLGGSSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Aflibercept (VEGFR1/VEGFR2-Fc) — VEGF Trap
AFLIBERCEPT_CHAIN = (
    "SDTGRPFVEMYSEIPEIIHMTEGRELVIPCRVTSPNITVTLKKFPLDTLIPDGKRIIWDSRKGFIISNATYKEIGLLTCEATVNGHLYKTNYLTHRQTNTIIDRVM"
    "HVEFLNPAGDQLILFPVISERLQSRVEGAQHSIESSSQKVTREDGEPALCSLHSEYGFSEAVIDHVSGDTVSFMKHPTGIFAGENFTLKFNGTCTKACNLREARNETHQDLYTCYASVHEPQKNSYAYQIKGGSPWPPPCQYRAQKETTYLNSHSWPVNQAEINVFEASSGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
    "EPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Rilonacept (IL1R-Fc) — IL-1 Trap
RILONACEPT_CHAIN = (
    "QPVANDKYELDVDVKDIIITTPNMFSTPSDYRESKYGQCWYAGTQRTISGRFPITFSALGLHYGYNFIYMKWNQRISNVDSETSNTLQYLWFEDLQPRFMCNITQLEKPNMPQLILQVEAKNQ"
    "TSYPCRENEKSPRMCRTDFTGTWKNHKNRFMPLITSEIDMQDLKSVSKCSQDLNCTYWSENVHRCGPWYLTQLNYNKTFCEPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Romiplostim (TPO-peptide-Fc) — thrombopoietin mimetic peptide fused to Fc
ROMIPLOSTIM_CHAIN = (
    "IEGPTLRQWLAARA"
    "GGGGGIEGPTLRQWLAARA"
    "EPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Dulaglutide (GLP1-Fc)
DULAGLUTIDE_CHAIN = (
    "HGEGTFTSDVSSYLEEQAAKEFIAWLVKGGGGGGGSGGGGSGGGGSAEPKSSDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

# Alefacept (LFA3-Fc)
ALEFACEPT_CHAIN = (
    "EYKNSVTLKDKVELMYPVKYNEDSFDVHIKGPSILNLKIHRDKDGTYVCIALNHFTIFDLNQTPEDSSTYMCEVDHYRNSTFQMHINISQDTSFSKSADKDSCFQFQEIKQLDAGIYECKLHEFTIEENNYTDLKVTQPVLQKLQQFVNESCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK"
)

FUSION_TEMPLATES = [
    ("etanercept", ETANERCEPT_CHAIN),
    ("abatacept", ABATACEPT_CHAIN),
    ("belatacept", BELATACEPT_CHAIN),
    ("aflibercept", AFLIBERCEPT_CHAIN),
    ("rilonacept", RILONACEPT_CHAIN),
    ("romiplostim", ROMIPLOSTIM_CHAIN),
    ("dulaglutide", DULAGLUTIDE_CHAIN),
    ("alefacept", ALEFACEPT_CHAIN),
]


# ═══════════════════════════════════════════════════════════════════════
#  Mutation utilities
# ═══════════════════════════════════════════════════════════════════════

def mutate_sequence(seq: str, n_mutations: int, rng: np.random.RandomState) -> str:
    """Introduce n_mutations random AA substitutions into seq."""
    seq_list = list(seq)
    length = len(seq_list)
    positions = rng.choice(length, size=min(n_mutations, length), replace=False)
    for pos in positions:
        original = seq_list[pos]
        candidates = [a for a in AA if a != original]
        seq_list[pos] = rng.choice(candidates)
    return "".join(seq_list)


def compute_record(name, mol_class, hc_seq, lc_seq, source):
    """Build a full feature record dict."""
    combined = hc_seq + lc_seq if lc_seq else hc_seq
    feats = compute_sequence_features(combined)
    if not feats:
        return None
    n_chains = (1 if len(hc_seq) >= 20 else 0) + (1 if len(lc_seq) >= 20 else 0)
    return {
        "name": name,
        "molecule_class": mol_class,
        "hc_sequence": hc_seq,
        "lc_sequence": lc_seq,
        "n_chains": n_chains,
        "n_unique_chains": n_chains,
        "source": source,
        **feats,
    }


# ═══════════════════════════════════════════════════════════════════════
#  Generate ADC curated data (~150 entries)
# ═══════════════════════════════════════════════════════════════════════

def generate_adc_data(target_count=150, seed=100):
    rng = np.random.RandomState(seed)
    records = []

    # First: exact template sequences (11 templates)
    for template_name, hc, lc in ADC_TEMPLATES:
        rec = compute_record(
            f"curated_adc_{len(records):03d}_{template_name}",
            "adc", hc, lc, "curated_adc"
        )
        if rec:
            records.append(rec)

    # Then: mutated variants — cycle through templates
    variant_idx = 0
    while len(records) < target_count:
        template_name, hc, lc = ADC_TEMPLATES[variant_idx % len(ADC_TEMPLATES)]
        n_mut = rng.randint(1, 6)  # 1–5 mutations per chain
        hc_mut = mutate_sequence(hc, n_mut, rng)
        lc_mut = mutate_sequence(lc, rng.randint(1, 4), rng)
        rec = compute_record(
            f"curated_adc_{len(records):03d}_{template_name}_v{variant_idx}",
            "adc", hc_mut, lc_mut, "curated_adc"
        )
        if rec:
            records.append(rec)
        variant_idx += 1

    return records


# ═══════════════════════════════════════════════════════════════════════
#  Generate fusion_protein curated data (~100 entries)
# ═══════════════════════════════════════════════════════════════════════

def generate_fusion_protein_data(target_count=100, seed=200):
    rng = np.random.RandomState(seed)
    records = []

    # First: exact template sequences (8 templates)
    for template_name, chain in FUSION_TEMPLATES:
        rec = compute_record(
            f"curated_fusionprot_{len(records):03d}_{template_name}",
            "fusion_protein", chain, "", "curated_fusion_protein"
        )
        if rec:
            records.append(rec)

    # Then: mutated variants
    variant_idx = 0
    while len(records) < target_count:
        template_name, chain = FUSION_TEMPLATES[variant_idx % len(FUSION_TEMPLATES)]
        n_mut = rng.randint(1, 8)  # 1–7 mutations
        chain_mut = mutate_sequence(chain, n_mut, rng)
        rec = compute_record(
            f"curated_fusionprot_{len(records):03d}_{template_name}_v{variant_idx}",
            "fusion_protein", chain_mut, "", "curated_fusion_protein"
        )
        if rec:
            records.append(rec)
        variant_idx += 1

    return records


# ═══════════════════════════════════════════════════════════════════════
#  Write CSV
# ═══════════════════════════════════════════════════════════════════════

COLUMNS = [
    "name", "molecule_class", "hc_sequence", "lc_sequence",
    "n_chains", "n_unique_chains", "source",
    "seq_length", "pI", "mw_kda", "gravy", "hydrophobicity",
    "deam_sites", "ox_sites", "cysteine_count", "acidic_residues", "basic_residues",
    "aromatic_frac", "pro_gly_frac", "cys_frac",
    "deam_density", "ox_density", "charge_ratio", "small_frac", "aliphatic_idx",
]


def write_csv(records, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for rec in records:
            writer.writerow(rec)
    print(f"  Written {len(records)} records to {path}")


if __name__ == "__main__":
    out_dir = os.path.join(PROJECT_ROOT, "data", "external", "curated")

    print("Generating ADC curated data...")
    adc_records = generate_adc_data(target_count=150)
    write_csv(adc_records, os.path.join(out_dir, "adc_curated.csv"))

    print("Generating fusion_protein curated data...")
    fp_records = generate_fusion_protein_data(target_count=100)
    write_csv(fp_records, os.path.join(out_dir, "fusion_protein_curated.csv"))

    print("Done.")
